repos:
-   repo: https://github.com/python-poetry/poetry
    rev: ''  # add version here
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
    -   id: poetry-export
        args: ["-f", "requirements.txt", "--without-hashes", "-o", "requirements.txt"]
        verbose: true