project:
  type: website
  output-dir: ../docs

# tell quarto to read the generated sidebar
metadata-files:
  - _sidebar.yml


quartodoc:
  # the name used to import the package you want to create reference docs for
  package: fave_recode
  style: pkgdown
  dir: reference
  # write sidebar data to this file
  sidebar: _sidebar.yml
  parser: google

  sections:
    - title: Rule Classes
      desc: Rule application classes
      contents:
        - rule_classes.Condition
        - rule_classes.Rule
        - rule_classes.RuleSet