project:
  type: website
  output-dir: ../docs


website:
  page-navigation: true
  navbar:
    left:
      - file: getting-started/overview.qmd
        text: Get Started
      - href: reference/
        text: Reference        
    right:
      - icon: github
        href: https://github.com/Forced-Alignment-and-Vowel-Extraction/fave-recode        
  sidebar:
      - id: get-started
        title: Get Started
        style: floating
        align: left
        contents:
          - getting-started/overview.qmd
          - section: Processing patterns
            contents: 
              - getting-started/single-file.qmd

format:
  html: 
    theme:
      light: flatly
      dark: darkly

# tell quarto to read the generated sidebar
metadata-files:
  - reference/_sidebar.yml

filters:
  - "interlinks"

interlinks:
  sources:
    python:
      url: https://docs.python.org/3/
    griffe:
      url: https://mkdocstrings.github.io/griffe/


quartodoc:
  # the name used to import the package you want to create reference docs for
  package: fave_recode
  style: pkgdown
  dir: reference
  # write sidebar data to this file
  sidebar: "reference/_sidebar.yml"
  parser: google
  render_interlinks: true
  sections:
    - title: Rule Classes
      desc: Rule application classes
      contents:
        - rule_classes.Condition
        - rule_classes.Rule
        - rule_classes.RuleSet