project:
  type: website
  output-dir: _site

website:
  title: fave-recode
  page-navigation: true
  image: assets/logo.png
  favicon: assets/logo.png
  navbar:
    left:
      - file: getting-started/overview.qmd
        text: Get Started
      - href: reference/
        text: Reference        
    right:
      - icon: github
        href: https://github.com/Forced-Alignment-and-Vowel-Extraction/fave-recode        
  sidebar:
    - id: get-started
      logo: assets/logo.png
      collapse-level: 3
      title: Get Started
      style: floating
      align: left
      contents:
        - getting-started/overview.qmd
        - section: Processing patterns
          contents: 
            - getting-started/single-file.qmd
            - getting-started/directory.qmd
        - section: Customizing a recoding scheme
          contents:
            - getting-started/rule-scheme-basics.qmd
            - getting-started/rule-application.qmd
            - section: Details
              contents:
                - getting-started/condition-attributes.qmd
                - getting-started/condition-relations.qmd
        - section: Labelset Parsing
          contents:
            - getting-started/label_set_parser.qmd

format:
  html: 
    theme:
      light: [flatly, styles/light.scss]
      dark: [darkly, styles/dark.scss]
    css: styles/styles.css
    toc: true
  

# tell quarto to read the generated sidebar
metadata-files:
  - reference/_sidebar.yml

filters:
  - "interlinks"
  - codeblocklabel

interlinks:
  fast: true
  sources:
    numpy:
      url: https://numpy.org/doc/stable/
    python:
      url: https://docs.python.org/3/
    aligned_textgrid:
      url: https://forced-alignment-and-vowel-extraction.github.io/alignedTextGrid/ 

resources: 
  - objects.inv

quartodoc:
  # the name used to import the package you want to create reference docs for
  package: fave_recode
  style: pkgdown
  dir: reference
  # write sidebar data to this file
  sidebar: "reference/_sidebar.yml"
  parser: google
  render_interlinks: true
  sections:
    - title: Rule Classes
      desc: Rule application classes
      contents:
        - rule_classes.Condition
        - rule_classes.Rule
        - rule_classes.RuleSet
    - title: Label Set Parsers
      desc: Label set parsers
      contents:
        - labelset_parser.LabelSetParser
        - labelset_parser.LabelSetParserProperties   
    - title: Relations
    - subtitle: "`in`, `not in`"
      contents:
        - relations.in_relation
        - relations.not_in_relation
    - subtitle: "equals, not equals"
      contents:
        - relations.equals_relation
        - relations.not_equals_relation
    - subtitle: "Regex match"
      contents:
        - relations.rematches_relation
        - relations.reunmatches_relation

