# labelset_parser.LabelSetParserProperties { #fave_recode.labelset_parser.LabelSetParserProperties }

`labelset_parser.LabelSetParserProperties(self, property=None)`

A property of the labelset, including rules that
ought to be applied and the SequenceInterval property to update.

## Parameters

| Name       | Type           | Description                                           | Default   |
|------------|----------------|-------------------------------------------------------|-----------|
| `property` | [dict](`dict`) | A dictionary defining the property. Defaults to None. | `None`    |

## Methods

| Name | Description |
| --- | --- |
| [validate_property](#fave_recode.labelset_parser.LabelSetParserProperties.validate_property) | Validate wellformedness of parser property |

### validate_property { #fave_recode.labelset_parser.LabelSetParserProperties.validate_property }

`labelset_parser.LabelSetParserProperties.validate_property(property)`

Validate wellformedness of parser property

#### Parameters

| Name     | Type           | Description         | Default    |
|----------|----------------|---------------------|------------|
| `parser` | [dict](`dict`) | property dictionary | _required_ |

#### Raises

| Type                     | Description                        |
|--------------------------|------------------------------------|
| [Exception](`Exception`) | Any errors raised by the validator |